### ISSUE TITLE
Regexp, PCRE memory leak

### ISSUE THREAD

**Issue by mt2d2** [fasterthanlime/jooc-legacy#26]
sdk/text/regexp/PCRE.ooc

The allocated pcre struct is never freed by pcre_free(), causing what I assume to be a leak. This is implemented in a finalizer, and assumedly waiting on support for that.

**Comment by nddrylliog** [comment]
Added finalizers support in j/ooc, and renamed destroy to **destroy** in PCRE so that it is, in fact, registered as a finalizer.

Commits:

http://github.com/nddrylliog/ooc/commit/75d96fb42f72027a5cbf35bf27e5d0c3e20de133

http://github.com/nddrylliog/ooc-docs/commit/1d23c823b7af3c39afeeb3c43149a7c32a6270ed

Enjoy!
